import { CardData, PlayerStats } from './types';

export const INITIAL_STATS: PlayerStats = {
  wealth: 50,
  connections: 30,
  achievements: 10,
  energy: 80,
  mood: 80,
};

export const MAX_TURNS = 50;
export const CARDS_TO_DRAW = 5;
export const CARDS_TO_PLAY = 3;

export const CARDS: CardData[] = [
  {
    id: 'study_ai',
    title: '学习 AI 工程',
    description: '深入钻研大模型与 Transformer。',
    effects: { achievements: 5, energy: -15, mood: -5 },
    type: 'study',
    emoji: '🤖',
  },
  {
    id: 'part_time_job',
    title: '兼职送外卖',
    description: '跑腿送餐赚点快钱。',
    effects: { wealth: 8, energy: -20, achievements: -1 },
    type: 'work',
    emoji: '🛵',
  },
  {
    id: 'club_activity',
    title: '学生会活动',
    description: '组织校园活动，锻炼能力。',
    effects: { connections: 6, energy: -10, achievements: 2 },
    type: 'social',
    emoji: '📢',
  },
  {
    id: 'dorm_gaming',
    title: '通宵开黑',
    description: '和室友一起上分。',
    effects: { mood: 15, energy: -25, achievements: -2 },
    type: 'leisure',
    emoji: '🎮',
  },
  {
    id: 'library_grind',
    title: '图书馆苦读',
    description: '备战期末考试。',
    effects: { achievements: 8, energy: -15, mood: -10 },
    type: 'study',
    emoji: '📚',
  },
  {
    id: 'networking_dinner',
    title: '校友晚宴',
    description: '结识成功的学长学姐。',
    effects: { connections: 10, wealth: -15, energy: -5 },
    type: 'social',
    emoji: '🥂',
  },
  {
    id: 'scholarship',
    title: '申请奖学金',
    description: '写申请书，希望能通过。',
    effects: { wealth: 15, energy: -10, mood: -5 },
    type: 'study',
    emoji: '💰',
  },
  {
    id: 'gym',
    title: '健身房锻炼',
    description: '举铁，增肌减脂。',
    effects: { energy: 10, mood: 5, wealth: -2 },
    type: 'leisure',
    emoji: '💪',
  },
  {
    id: 'date',
    title: '浪漫约会',
    description: '吃饭看电影。',
    effects: { mood: 20, wealth: -20, connections: 2 },
    type: 'social',
    emoji: '❤️',
  },
  {
    id: 'hackathon',
    title: '周末黑客松',
    description: '48小时极限开发一个创业项目。',
    effects: { achievements: 12, connections: 5, energy: -30, mood: 5 },
    type: 'study',
    emoji: '💻',
  },
  {
    id: 'internship_interview',
    title: '大厂面试',
    description: '准备并参加科技公司的面试。',
    effects: { achievements: 5, mood: -10, energy: -10 },
    type: 'work',
    emoji: '👔',
  },
  {
    id: 'help_counselor',
    title: '帮辅导员干活',
    description: '处理学院的行政琐事。',
    effects: { connections: 4, achievements: 1, energy: -5 },
    type: 'work',
    emoji: '📋',
  },
  {
    id: 'online_course',
    title: '网课考证',
    description: '完成 Coursera 专业证书。',
    effects: { achievements: 4, wealth: -5, energy: -5 },
    type: 'study',
    emoji: '🎓',
  },
  {
    id: 'travel',
    title: '周边游',
    description: '去附近的城市散散心。',
    effects: { mood: 25, wealth: -30, energy: -10 },
    type: 'leisure',
    emoji: '🚆',
  },
  {
    id: 'research_project',
    title: '加入实验室',
    description: '帮教授搬砖写论文。',
    effects: { achievements: 10, energy: -15, connections: 5 },
    type: 'study',
    emoji: '🔬',
  },
  {
    id: 'startup_idea',
    title: '构思创业',
    description: '在餐巾纸上画商业模式。',
    effects: { achievements: 2, mood: 5, energy: -5 },
    type: 'work',
    emoji: '💡',
  },
  {
    id: 'student_loan',
    title: '助学贷款',
    description: '借钱交学费。',
    effects: { wealth: 50, mood: -10 },
    type: 'event',
    emoji: '🏦',
  },
  {
    id: 'volunteer',
    title: '志愿服务',
    description: '帮助社区服务。',
    effects: { connections: 8, mood: 10, energy: -15 },
    type: 'social',
    emoji: '🤝',
  },
  {
    id: 'sleep_in',
    title: '睡懒觉',
    description: '翘掉早八的课。',
    effects: { energy: 20, achievements: -5 },
    type: 'leisure',
    emoji: '😴',
  },
  {
    id: 'campus_concert',
    title: '校园音乐节',
    description: '观看音乐社团的演出。',
    effects: { mood: 12, wealth: -5 },
    type: 'social',
    emoji: '🎸',
  },
];